#!/bin/bash -l 
#SBATCH --time=24:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --ntasks-per-core=1
#SBATCH --mem=120G
#SBATCH --account=yohes
#SBATCH --mail-user=qiuxx221@umn.edu
#SBATCH --partition=msismall 
#SBATCH --job-name=cov_cnv
#SBATCH --error=cov_cnv.err
#SBATCH --output=cov_cnv.out

cd /home/yohes/shared/ris/qiuxx221/cobalt/test
BED=/home/clinicalmdl/shared/references/germline_aws_references/exons_MSOC_PMS2CNVspecific.bed
BAMS=/home/yohes/shared/germline_GATK4/projects/20-05335_30Sep2020_MSOC072_MDL5545_smtest/data/20-05335_30Sep2020_MSOC072_MDL5545_smtest.bam
echo $BAMS
covcounter --bed $BED --bams $BAMS --threads 16 > 20-05335_30Sep2020_MSOC072_MDL5545_sm_yqtest.bed 
